#!/bin/bash
# Interactive helper — writes apps/ios/Config/Secrets.xcconfig for Supabase mode.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SECRETS_FILE="$SCRIPT_DIR/Config/Secrets.xcconfig"

echo ""
echo "=== Marvi Society — iOS Supabase Setup ==="
echo ""
echo "You need these from supabase.com → Project Settings → API:"
echo "  • Project URL (https://xxxx.supabase.co)"
echo "  • anon public key"
echo ""

read -r -p "Supabase Project URL: " SUPABASE_URL
read -r -p "Supabase anon key: " SUPABASE_ANON

if [[ -z "$SUPABASE_URL" || -z "$SUPABASE_ANON" ]]; then
  echo "Error: URL and anon key are required."
  exit 1
fi

# xcconfig treats // as a comment — escape URLs for build injection.
escape_xcconfig_url() {
  local url="$1"
  echo "${url/https:\/\//https:\/\$()\/}"
}

ESCAPED_URL="$(escape_xcconfig_url "$SUPABASE_URL")"

cat > "$SECRETS_FILE" <<EOF
// Generated by configure-supabase.sh — do not commit (gitignored)

MARVI_API_MODE = supabase
MARVI_SUPABASE_URL = $ESCAPED_URL
MARVI_SUPABASE_ANON_KEY = $SUPABASE_ANON

INFOPLIST_KEY_MARVI_SUPABASE_URL = \$(MARVI_SUPABASE_URL)
INFOPLIST_KEY_MARVI_SUPABASE_ANON_KEY = \$(MARVI_SUPABASE_ANON_KEY)
INFOPLIST_KEY_MARVI_API_MODE = \$(MARVI_API_MODE)
EOF

echo ""
echo "✓ Wrote $SECRETS_FILE"
echo ""
echo "Next steps:"
echo "  1. Run database migrations (see infra/supabase/ALL_MIGRATIONS_COMBINED.sql)"
echo "  2. Open MarviSociety.xcodeproj in Xcode"
echo "  3. Build & Run on a real iPhone for Sign in with Apple"
echo ""
